argo-cd:
  server:
    extraArgs:
     - --insecure
    config:
      accounts.image-updater: apiKey
      application.instanceLabelKey: argocd.argoproj.io/instance
      url: http://pass-vars-mini-argocd-client1
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
      enabled: true
      extraPaths: []
      hosts:
        - pass-vars-mini-argocd-client1.example.com
      https: false
      ingressClassName: ''
      labels: {}
      pathType: Prefix
      paths:
        - /
      tls: []