argo-cd:
  server:
    additionalApplications:
    - name: guestbook
      namespace: client1-argo
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers: []
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: client1-argo-ns1
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      info:
      - name: url
        value: https://argoproj.github.io/
    - name: helm-hooks
      namespace: client1-argo
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers: []
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-hooks
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: client1-argo-ns2
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true