argo-cd:
  server:
    additionalProjects:
    - name: client1-project-1
      namespace: client1-argo
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers: []
      description: Example Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: client1-argo-ns1
        server: https://kubernetes.default.svc
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
      clusterResourceWhitelist:
      - group: ''
        kind: Namespace
    - name: client1-project-2
      namespace: client1-argo
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers: []
      description: Example Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: client1-argo-ns2
        server: https://kubernetes.default.svc
      namespaceResourceWhitelist:
      - group: '*'
        kind: '*'
      clusterResourceWhitelist:
      - group: ''
        kind: Namespace