apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-w-vars
  namespace: client1-argo-w-vars
spec:
  destination:
    name: ''
    namespace: helm-guestbook-w-vars
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-example-apps/helm-guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    helm:
      parameters:
        - name: replicaCount
          value: {{ .Values.client.helmguestbook.replicaCount }}
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true